apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
        - name: provider
          image: srt0422/morpheus-marketplace-provider:v0.0.6
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - containerPort: 3333
              name: provider
            - containerPort: 8080
              name: metrics
            - containerPort: 8082
              name: health
          env:
            # Wallet configuration
            - name: WALLET_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: provider-secrets
                  key: wallet-private-key
            
            # Blockchain configuration
            - name: DIAMOND_CONTRACT_ADDRESS
              value: "0xb8C55cD613af947E73E262F0d3C54b7211Af16CF"
            - name: MOR_TOKEN_ADDRESS
              value: "0x34a285a1b1c166420df5b6630132542923b5b27e"
            - name: EXPLORER_API_URL
              value: "https://api-sepolia.arbiscan.io/api"
            - name: ETH_NODE_CHAIN_ID
              value: "421614"
            - name: ETH_NODE_ADDRESS
              value: "https://sepolia-rollup.arbitrum.io/rpc"
            - name: ETH_NODE_USE_SUBSCRIPTIONS
              value: "false"
            - name: ETH_NODE_LEGACY_TX
              value: "false"
            
            # Environment
            - name: ENVIRONMENT
              value: "development"
            
            # Service configuration
            - name: PROXY_ADDRESS
              value: "0.0.0.0:3333"
            - name: WEB_ADDRESS
              value: "0.0.0.0:8082"
            - name: WEB_PUBLIC_URL
              value: "http://35.227.134.166:8082"
            - name: PROXY_STORE_CHAT_CONTEXT
              value: "true"
            - name: PROXY_STORAGE_PATH
              value: "/app/data/"
            
            # Config paths
            - name: MODELS_CONFIG_PATH
              value: "/app/data/models-config.json"
            - name: RATING_CONFIG_PATH
              value: "/app/data/rating-config.json"
            
            # Logging
            - name: LOG_COLOR
              value: "true
              
          volumeMounts:
            - name: provider-data
              mountPath: /app/data
      volumes:
        - name: provider-data
          persistentVolumeClaim:
            claimName: provider-data