apiVersion: v1
kind: ConfigMap
metadata:
  name: models-config
data:
  models-config.json: |-
    {
      "$schema": "./internal/config/models-config-schema.json",
      "models": [
        {
          "modelId": "0x5781caf0457ceda99459aa9f8a86b98675b45fa27788b9a058c5c184e640065e",
          "modelName": "llama2",
          "apiType": "openai",
          "apiUrl": "https://9079161191267303424.us-central1-fasttryout.prediction.vertexai.goog/v1/projects/101868473812/locations/us-central1/endpoints/9079161191267303424",
          "apiKey": "19dcf7e801e37e40e078d639cfeab6c7a3403ce0"
        }
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
data:
  proxy.conf: |-
    {
      "users": {
        "admin": {
          "password": "admin123",
          "role": "admin"
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-ip-script
data:
  get-service-ip.sh: |-
    #!/bin/sh
    set -e
    
    # Try to get service IP using k8s API with retries
    for i in $(seq 1 60); do
      SERVICE_IP=$(wget -qO- --header "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
        --no-check-certificate \
        https://kubernetes.default.svc/api/v1/namespaces/$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)/services/provider-service \
        | grep -o '"ip": "[^"]*' | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' | head -1)
        
      if [ -n "$SERVICE_IP" ]; then
        echo "http://$SERVICE_IP:8082" > /app/config/web_public_url
        chmod 644 /app/config/web_public_url
        echo "Service IP detected: $SERVICE_IP"
        exit 0
      fi
      
      echo "Waiting for service IP... (attempt $i/60)"
      sleep 2
    done
    
    echo "Failed to get service IP, using fallback"
    echo "http://provider-service:8082" > /app/config/web_public_url
    chmod 644 /app/config/web_public_url
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      hostAliases:
      - ip: "34.118.232.160"  # Use your cluster IP here
        hostnames:
        - "provider-service"
      initContainers:
        - name: init-config
          image: busybox
          command: ['sh', '-c', 'cp /tmp/proxy.conf /app/config/proxy.conf && chmod 644 /app/config/proxy.conf']
          volumeMounts:
            - name: proxy-config-template
              mountPath: /tmp/proxy.conf
              subPath: proxy.conf
            - name: config-dir
              mountPath: /app/config
        - name: init-service-ip
          image: busybox
          command: ['sh', '-c', 'sh /tmp/get-service-ip.sh']
          volumeMounts:
            - name: service-ip-script
              mountPath: /tmp/get-service-ip.sh
              subPath: get-service-ip.sh
            - name: config-dir
              mountPath: /app/config
          securityContext:
            runAsUser: 0
      containers:
        - name: provider
          image: srt0422/morpheus-marketplace-provider:${VERSION}
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - containerPort: 3333
              name: provider
            - containerPort: 8082
              name: health
          env:
            # Wallet configuration
            - name: WALLET_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: provider-secrets
                  key: wallet-private-key

            # TESTNET VALUES
            - name: DIAMOND_CONTRACT_ADDRESS
              value: "0xb8C55cD613af947E73E262F0d3C54b7211Af16CF"
            - name: MOR_TOKEN_ADDRESS
              value: "0x34a285a1b1c166420df5b6630132542923b5b27e"
            - name: EXPLORER_API_URL
              value: "https://api-sepolia.arbiscan.io/api"
            - name: ETH_NODE_CHAIN_ID
              value: "421614"
            - name: ENVIRONMENT
              value: "development"
            - name: BLOCKSCOUT_API_URL
              value: "https://api-sepolia.arbiscan.io/api"

            # COMMON
            - name: PROXY_ADDRESS
              value: "0.0.0.0:3333"
            - name: WEB_ADDRESS
              value: "0.0.0.0:8082"
            - name: WEB_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: dynamic-web-url
                  key: url
                  optional: true
            - name: MODELS_CONFIG_PATH
              value: "/app/data/models-config.json"
            - name: ETH_NODE_USE_SUBSCRIPTIONS
              value: "false"
            - name: ETH_NODE_ADDRESS
              value: "https://sepolia-rollup.arbitrum.io/rpc"
            - name: ETH_NODE_LEGACY_TX
              value: "false"
            - name: PROXY_STORE_CHAT_CONTEXT
              value: "true"
            - name: PROXY_STORAGE_PATH
              value: "./data/"
            - name: LOG_COLOR
              value: "true"
            - name: AUTH_CONFIG_FILE_PATH
              value: "/app/config/proxy.conf"

          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - |
                    if [ -f /app/config/web_public_url ]; then
                      URL=$(cat /app/config/web_public_url)
                      export WEB_PUBLIC_URL="$URL"
                    fi

          volumeMounts:
            - name: provider-data
              mountPath: /app/data
            - name: models-config
              mountPath: /app/data/models-config.json
              subPath: models-config.json
            - name: config-dir
              mountPath: /app/config
      volumes:
        - name: provider-data
          persistentVolumeClaim:
            claimName: provider-data
        - name: models-config
          configMap:
            name: models-config
        - name: proxy-config-template
          configMap:
            name: proxy-config
        - name: service-ip-script
          configMap:
            name: service-ip-script
        - name: config-dir
          emptyDir: {}