name: Node-RED Custom Nodes Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      RUN_INTEGRATION_TEST: ${{ secrets.RUN_INTEGRATION_TEST }}
      TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
      TEST_REGION: ${{ secrets.TEST_REGION }}
      TEST_DOCKER_REGISTRY: ${{ secrets.TEST_DOCKER_REGISTRY }}
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      TEST_WALLET_KEY: ${{ secrets.TEST_WALLET_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Authenticate to Google Cloud
        if: env.RUN_INTEGRATION_TEST == 'true'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        if: env.RUN_INTEGRATION_TEST == 'true'
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.TEST_PROJECT_ID }}

      - name: Authenticate Docker with GCR
        if: env.RUN_INTEGRATION_TEST == 'true'
        run: gcloud auth configure-docker

      - name: Run integration tests
        if: env.RUN_INTEGRATION_TEST == 'true'
        run: node test/integration-test.js 