name: nfa-proxy

services:
  nfa-proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
      args:
        TARGETOS: linux
        TARGETARCH: arm64
        TARGETPLATFORM: linux/arm64
      platforms:
        - linux/arm64
    # image: nfa-proxy:latest
    env_file:
      - .env
    environment:
      - PORT=${PORT:-8080}
      - MARKETPLACE_URL=${MARKETPLACE_URL:-http://lumerin-node-api:8083}
      - SESSION_DURATION=${SESSION_DURATION:-1h}
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - MODEL_ID=${MODEL_ID}
      - DEFAULT_PORT=${DEFAULT_PORT:-8080}
      - MARKETPLACE_PORT=${MARKETPLACE_PORT:-8083}
      - LUMERIN_NODE_API=${LUMERIN_NODE_API:-http://lumerin-node-api:8083}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - SESSION_EXPIRATION_SECONDS=${SESSION_EXPIRATION_SECONDS:-1800}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "${PORT:-8080}:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - lumerin-network

networks:
  lumerin-network:
    name: lumerin-network
    external: true

volumes:
  provider-data:
    driver: local