apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "22"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"nfa-proxy-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nfa-proxy"}},"template":{"metadata":{"labels":{"app":"nfa-proxy"}},"spec":{"containers":[{"env":[{"name":"PORT","value":"8080"},{"name":"MARKETPLACE_URL","value":"http://34.118.234.36:8083/v1/chat/completions"},{"name":"SESSION_DURATION","value":"1h"},{"name":"WALLET_ADDRESS","valueFrom":{"secretKeyRef":{"key":"wallet-address","name":"nfa-proxy-secrets"}}},{"name":"WALLET_PRIVATE_KEY","valueFrom":{"secretKeyRef":{"key":"wallet-private-key","name":"nfa-proxy-secrets"}}},{"name":"DEFAULT_PORT","value":"8080"},{"name":"MARKETPLACE_PORT","value":"8083"},{"name":"BLOCKSCOUT_API_URL","value":"https://api-sepolia.arbiscan.io/api"},{"name":"ETH_NODE_ADDRESS","value":"https://sepolia-rollup.arbitrum.io/rpc"},{"name":"ETH_NODE_CHAIN_ID","value":"421614"},{"name":"DIAMOND_CONTRACT_ADDRESS","value":"0xb8C55cD613af947E73E262F0d3C54b7211Af16CF"},{"name":"MOR_TOKEN_ADDRESS","value":"0x34a285a1b1c166420df5b6630132542923b5b27e"},{"name":"ENVIRONMENT","value":"development"},{"name":"MODELS_CONFIG_PATH","value":"/app/models-config.json"}],"image":"srt0422/morpheus-marketplace-consumer:latest","livenessProbe":{"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":30,"periodSeconds":30},"name":"nfa-proxy","ports":[{"containerPort":8080}],"volumeMounts":[{"mountPath":"/app/models-config.json","name":"models-config","subPath":"models-config.json"}]}],"volumes":[{"configMap":{"name":"nfa-proxy-models-config"},"name":"models-config"}]}}}}
  creationTimestamp: "2024-12-30T06:28:15Z"
  generation: 25
  name: nfa-proxy-deployment
  namespace: default
  resourceVersion: "43776439"
  uid: 7b89bd9a-44f8-4936-9262-fcd9c764171f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nfa-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nfa-proxy
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: MARKETPLACE_URL
          value: http://34.118.234.36:8083/v1/chat/completions
        - name: SESSION_DURATION
          value: 1h
        - name: WALLET_ADDRESS
          valueFrom:
            secretKeyRef:
              key: wallet-address
              name: nfa-proxy-secrets
        - name: WALLET_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: wallet-private-key
              name: nfa-proxy-secrets
        - name: DEFAULT_PORT
          value: "8080"
        - name: MARKETPLACE_PORT
          value: "8083"
        - name: BLOCKSCOUT_API_URL
          value: https://api-sepolia.arbiscan.io/api
        - name: ETH_NODE_ADDRESS
          value: https://sepolia-rollup.arbitrum.io/rpc
        - name: ETH_NODE_CHAIN_ID
          value: "421614"
        - name: DIAMOND_CONTRACT_ADDRESS
          value: 0xb8C55cD613af947E73E262F0d3C54b7211Af16CF
        - name: MOR_TOKEN_ADDRESS
          value: 0x34a285a1b1c166420df5b6630132542923b5b27e
        - name: ENVIRONMENT
          value: development
        - name: MODELS_CONFIG_PATH
          value: /app/models-config.json
        image: srt0422/morpheus-marketplace-consumer:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: nfa-proxy
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/models-config.json
          name: models-config
          subPath: models-config.json
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: nfa-proxy-models-config
        name: models-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-02-07T16:38:14Z"
    lastUpdateTime: "2025-02-07T16:38:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-12-30T06:57:32Z"
    lastUpdateTime: "2025-02-07T16:39:16Z"
    message: ReplicaSet "nfa-proxy-deployment-6ddcf966fb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 25
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
